### ISSUE TITLE
Broken Link to required plugin

### ISSUE THREAD

**Issue by csBlueChip** [6o6o/fft-descreen#5]
Gimp have decided to ditch their plugins database, so your link to the required FFT plugin is 404.

The official repo is archived at https://github.com/pixlsus/registry.gimp.org_static/tree/master/registry.gimp.org/files

Can you fix your links please? Or perhaps just specify the filenames of anything required.

Thanks
BC

**Comment by 6o6o** [comment]
Alternatively you can use web archive to view the snapshot at the time it was published

http://web.archive.org/web/20161118075437/http://registry.gimp.org/node/24411
http://web.archive.org/web/20161118081031/http://registry.gimp.org/node/19596
